# named list of all robots
robots:
  # cf7:
  #   enabled: true
  #   uri: radio://0/80/2M/E7E7E7E707
  #   initial_position: [0.0, 0.0, 0.0]
  #   type: cf21  # see robot_types

  # cf4:
  #   enabled: true
  #   uri: radio://0/80/2M/E7E7E7E704
  #   initial_position: [0.0, 0.0, 0.0]
  #   type: cf21  # see robot_types
    
  cf6:
    enabled: true
    uri: radio://0/80/2M/E7E7E7E706
    initial_position: [0.0, 0.0, 0.0]
    type: cf21  # see robot_types

  # cf9:
  #   enabled: true
  #   uri: radio://0/80/2M/E7E7E7E709
  #   initial_position: [0.0, 0.0, 0.0]
  #   type: cf21  # see robot_types

  # cf2:
  #   enabled: true
  #   uri: radio://0/80/2M/E7E7E7E702
  #   initial_position: [0.0, 0.0, 0.0]
  #   type: cf21  # see robot_types
  # cf3:
  #   enabled: true
  #   uri: radio://0/80/2M/E7E7E7E703
  #   initial_position: [0.0, 0.0, 0.0]
  #   type: cf21  # see robot_types
  # cf4:
  #   enabled: true
  #   uri: radio://0/80/2M/E7E7E7E704
  #   initial_position: [0.0, 0.0, 0.0]
  #   type: cf21  # see robot_types
  
# Definition of the various robot types
robot_types:
  cf21:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: default
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V

  cf21_mocap_deck:
    motion_capture:
      enabled: true
      # only if enabled; see motion_capture.yaml
      marker: default
      dynamics: default
    big_quad: false
    battery:
      voltage_warning: 3.8  # V
      voltage_critical: 3.7 # V


# global settings for all robots
all:
  # firmware logging for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_logging:
    enabled: true
    # default_topics:
     # remove to disable default topic
      # pose:
      #   frequency: 100 # Hz
    custom_topics:
      pos:
        frequency: 100 # Hz
        vars: ["stateEstimate.x", "stateEstimate.y", "stateEstimate.z"]
      quat:
        frequency: 100 # Hz
        vars: ["stateEstimate.qw", "stateEstimate.qx", "stateEstimate.qy", "stateEstimate.qz",]
      vel:
        frequency: 100 # Hz
        vars: ["stateEstimate.vx", "stateEstimate.vy", "stateEstimate.vz"]
      # motors:
      #   frequency: 100
      #   vars: ['motors.m1', 'motors.m2', 'motors.m3', 'motors.m4']
      # thrust:
      #   frequency: 100
      #   vars: ["controller.cmd_thrust", "controller.actuatorThrust"]
      # rpy:
      #   frequency: 100 # Hz
      #   vars: ["stateEstimate.roll", "stateEstimate.pitch", "stateEstimate.yaw"]
  # firmware parameters for all drones (use robot_types/type_name to set per type, or
  # robots/drone_name to set per drone)
  firmware_params:
    commander:
      enHighLevel: 1
    stabilizer:
      estimator: 2 # 1: complementary, 2: kalman
      controller: 2 # 1: PID, 2: mellinger
    # ring:
    #   effect: 16 # 6: double spinner, 7: solid color, 16: packetRate
    #   solidBlue: 255 # if set to solid color
    #   solidGreen: 0 # if set to solid color
    #   solidRed: 0 # if set to solid color
    #   headlightEnable: 0
    locSrv:
      extPosStdDev: 1e-3
      extQuatStdDev: 0.5e-1
    # kalman:
    #   resetEstimation: 1
  broadcasts:
    num_repeats: 15 # number of times broadcast commands are repeated
    delay_between_repeats_ms: 1 # delay in milliseconds between individual repeats
